# Generated by Django 4.2.5 on 2023-09-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('img', models.CharField()),
                ('location', models.CharField()),
                ('status', models.BooleanField(default=False)),
                ('like_cnt', models.IntegerField(default=0)),
                ('chat_cnt', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
        ),
    ]
