# Generated by Django 4.2.5 on 2023-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
