# Generated by Django 4.2.5 on 2023-09-27 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sure_app', '0003_remove_message_user_message_receiver_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sure_app.message'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('manner_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_review', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
