# Generated by Django 4.2.5 on 2023-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sure_app', '0005_alter_like_goods_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
