# Generated by Django 4.2.5 on 2023-09-28 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sure_app", "0007_alter_message_img_alter_message_receiver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="buyer",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="seller",
            new_name="user2",
        ),
    ]
