# Generated by Django 4.2.5 on 2023-09-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sure_app", "0008_rename_buyer_chat_user1_rename_seller_chat_user2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="sure_app.chat",
            ),
        ),
    ]
