# Generated by Django 4.2.5 on 2023-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sure_app', '0009_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_certification',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
